_services="com.system76.PowerDaemon.service"

_stop_services() {
  for service in $_services; do
    if /usr/bin/systemctl -q is-active $service >/dev/null 2>&1; then
      /usr/bin/systemctl stop $service >/dev/null 2>&1
    fi
  done
}

_restore_services() {
  for service in $_services; do
    if /usr/bin/systemctl -q is-enabled $service >/dev/null 2>&1; then
      /usr/bin/systemctl start $service > /dev/null 2>&1
    fi
  done
}

post_install() {
cat << EOF

    The System76 Power package provides the following system services:

        com.system76.PowerDaemon.service    System76 power support

    And the following application

        system76-power                      System76 power CLI interface

EOF
}

pre_upgrade() {
  if /usr/bin/systemctl -q is-enabled system76-power.service >/dev/null 2>&1; then
    /usr/bin/systemctl stop system76-power.service >/dev/null 2>&1
    cat << EOF
    The systemd unit have been renamed to com.system76.PowerDaemon.service, you
    need to disable the old name and enable the new one:
        systemctl disable system76-power.service
        systemctl enable com.system76.PowerDaemon.service
EOF
  fi
  _stop_services
}

post_upgrade() {
  _restore_services
  post_install
}

pre_remove() {
  _stop_services
}

post_remove() {
  cat << EOF

    Remember to disable any leftover System76 power services:
        systemctl disable com.system76.PowerDaemon.service

EOF
}
